### ISSUE TITLE
Aider version?

### ISSUE THREAD

**Issue by jontstaz** [morph-labs/rift#139]
Hi,

I've been using Aider a lot just via my terminal/cli. I just installed Rift to check it out but it seems that it's using an old version of Aider (v0.91)? Is there any way to update the version of Aider? And for that matter is it possible to update all of the programs it uses (GPT Engineer, Smol Dev, etc.)? I like the idea of Rift but if it can't access the latest version of the programs then I'd rather just use Aider/GPT Engineer natively.

Cheers,

**Comment by jesse-michael-han** [comment]
Hello, thanks for the feedback! We maintain forks of open-source third-party agents like Aider, Smol, and GPT-Engineer. You can find their urls in `rift-engine/pyproject/toml`. You can always try rebasing those forks on their most recent versions and submitting a PR. Otherwise we'll get to them eventually as well.

**Comment by jesse-michael-han** [comment]
Aider is now up-to-date as of Rift 2.0.1: https://github.com/morph-labs/rift/pull/141
